### ISSUE TITLE
Cliqz include UI to disable the search, but the experiment remains enabled

### ISSUE THREAD

**Issue by flodolo** [cliqz-oss/browser-core#35]
Steps to reproduce:
* Install Cliqz from https://testpilot.firefox.com/experiments/cliqz
* Use it in a location outside of Germany, start typing, you'll get a warning at the bottom of the search bar to disable search integration.

If you disable it, the add-on still shows up as enabled, but search integration is disabled (new tab is still there). Reinstalling the add-on doesn't re-enable search integration.

Tried searching in about:config, but there are a ton of preferences set by cliqz.

**Comment by luciancor** [comment]
Thanks for your feedback @flodolo  !

This is an expected behavior. For users using CLIQZ outside Germany AND using a non-german browser (locale) we have a notification in the footer. This is what you experienced (attached also a screenshot for it).  
Using this UI you can indeed disable the search part until we will have better results for your country. Very important is that we only disable the search and not the other features of CLIQZ like our NewTab page or Human Web technology.

If you want to control this mechanism more precisely from about:config here are the 2 prefs controlling the mechanism:
     - “extensions.cliqz.ignored_location_warning” (boolean)  :
           - true - hides the message forever (set when clicking on “OK” ) and keeps the best search we can offer you at this moment (german)
           - false - we keep showing the message
           - initial value is empty and we default to “false”
     - “extensions.cliqz.cliqz_core_disabled” (boolean)  :
           - true - disables CLIQZ search - we fallback to Firefox UI and results (history)
           - false - search works by default
           - initial value is empty and we default to “false”
           - IMPORTANT: this pref change requires a browser restart 

![ouside](https://cloud.githubusercontent.com/assets/5583036/21882237/e150c624-d8a9-11e6-98a6-1fa67f9d4323.png)
