### ISSUE TITLE
"The address isn’t valid" when going back to about:cliqz

### ISSUE THREAD

**Issue by past** [cliqz-oss/browser-core#4]
When I click on a "wellsfargo.com" tile on the new Cliqz homepage, and then click the Back button to go back to the new Cliqz homepage, it gives me an error saying "The address isn’t valid". Refreshing the page seems to re-render the new homepage correctly, but I always seem to get that weird error when clicking back. This was tested using Developer Edition. The Browser Console contains the following error:

`NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIWebNavigation.goBack] browser-child.js:297
`

**Comment by past** [comment]
Fixed by #17.

**Comment by luciancor** [comment]
Just checked it again in FF 49, 50, 51, 52 and 53 and everything seems fine at my end.
For non e10s this fix doesn't change anything and the user can navigate back to about:cliqz while when e10s is enabled we do not allow back navigation to about:cliqz after the user goes somewhere using his top sites or a news entry.

@past maybe the build was not complete in your case?
In order to force a full build of the extension and freshtab an extra parameter is requires "--freshtab"

Can you please try again with the following line ?
./fern.js build confi/test-pilot.json --freshtab

**Comment by past** [comment]
Hmm, not sure what happened, but now I definitely see it works again. Sorry for the noise.
